// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx7X1PKwB-56_Pgq0Mrra8rfgIk876Mvc',
    appId: '1:364834271222:web:938049212f8bf02de4e1d7',
    messagingSenderId: '364834271222',
    projectId: 'pawpoint-admin',
    authDomain: 'pawpoint-admin.firebaseapp.com',
    storageBucket: 'pawpoint-admin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwrbNyXBZVJmJOHhZLYFizXxjN1Eob-qc',
    appId: '1:364834271222:android:57146bc0876867fce4e1d7',
    messagingSenderId: '364834271222',
    projectId: 'pawpoint-admin',
    storageBucket: 'pawpoint-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdyOyiYTIiDlocfwLDo25ksJ9xyIDIYcM',
    appId: '1:364834271222:ios:b418187469611b5de4e1d7',
    messagingSenderId: '364834271222',
    projectId: 'pawpoint-admin',
    storageBucket: 'pawpoint-admin.firebasestorage.app',
    iosBundleId: 'com.example.pawpointAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdyOyiYTIiDlocfwLDo25ksJ9xyIDIYcM',
    appId: '1:364834271222:ios:b418187469611b5de4e1d7',
    messagingSenderId: '364834271222',
    projectId: 'pawpoint-admin',
    storageBucket: 'pawpoint-admin.firebasestorage.app',
    iosBundleId: 'com.example.pawpointAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx7X1PKwB-56_Pgq0Mrra8rfgIk876Mvc',
    appId: '1:364834271222:web:5e6996191e6d671ee4e1d7',
    messagingSenderId: '364834271222',
    projectId: 'pawpoint-admin',
    authDomain: 'pawpoint-admin.firebaseapp.com',
    storageBucket: 'pawpoint-admin.firebasestorage.app',
  );
}
